### ISSUE TITLE
This is fantastic!  Just curious if source code is available? 

### ISSUE THREAD

**Issue by Skrell** [Osmagtor/AppSwitcher#1]
<see title>

**Comment by Osmagtor** [comment]
Thanks! And sure! I guess there are some bits of code that you want to reuse yourself. Before making it available though, I'll try to document what each part of the code does so it can be easier to read through.

**Comment by Osmagtor** [comment]
And [here](https://github.com/Osmagtor/AppSwitcher/releases/tag/v7.0.7) it is
