### ISSUE TITLE
recommendation

### ISSUE THREAD

**Issue by Skrell** [Osmagtor/AppSwitcher#2]
I think you should leave the behavior to have "minimized windows going to the end of the app list" as it makes it much quicker to swap between active windows on your desktop.  IMO, minimized windows are typically accessed less frequently hence their reason for being "minimized" .

**Comment by Osmagtor** [comment]
After conducting a good deal of research last weekend to try to get it working, I learnt that _that_ used to be default behaviour of the built-in Task Switcher in Windows 7 and earlier. However, after having used Windows 10 and 11 (where minimized windows retain their position based on their recency) for a few years now, I had come to expect the exact opposite behaviour. Knowing that and seeing as it's really a matter of preference, if I do manage to implement it, it'd be something that can be toggled from the menu in the tray icon.

**Comment by Skrell** [comment]
That's interesting and I did not know that!   A toggle would be fantastic if possible!
