### ISSUE TITLE
Feature request, icon size

### ISSUE THREAD

**Issue by nimbling** [Osmagtor/AppSwitcher#3]
@Osmagtor, you are a life safer. Thank you. The native windows task switcher was driving me nuts, and you fixed it.

I'd like to request a feature :)
Could we perhaps, in the "settings.ini" get a setting to resize the icons? I'd like them to be around 200, maybe 256 ish, but if we could enter a setting there it would help a great deal.

Thanks for having a look!

**Comment by Osmagtor** [comment]
Hi, @nimbling. I'm glad you like my app! I've kept development on the sidelines to focus on my classes, but I'm planning to get back to the project soon and write all the code from scratch. It would allow me to make it more robust, put everything I've learnt over the past few months into use and even make it cross-platform! I'll keep your input in mind.

**Comment by nimbling** [comment]
Omg! that’s amazing news :) looking forward to it on both platforms. This is just a way more sane way to interact with app switching. Again: thank you! :)

**Comment by nimbling** [comment]
[App Switcher.zip](https://github.com/Osmagtor/AppSwitcher/files/15399459/App.Switcher.zip)
This version of the .AHK has:

- Increased Icon Size (Be ready for pixelated hell... some app icons are tiny!)
- Quits the switcher (not the selected App) when pressing ESC
- Keeps all windows to the front (does not send windows of an app to the background) when switching within an App

* Sometimes throws an error when I switch Apps too fast, but I'll just press "reload" and still be happy with this script's existence.

Still needs to be packaged using AHK2EXE.
I'm super happy with it, I hope someone else will be, too.

**Comment by Osmagtor** [comment]
I've added your first two ideas to the app. I'll keep working on a better solution to change between windows of the same app. I'm going to close the issue for now. Thanks for your input!
